project_id = "ylmrmidgxhcthwmoebzl"

[functions.asaas-pix]
verify_jwt = false

[functions.asaas-balance]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-pixout]
verify_jwt = false

[functions.asaas-approval-webhook]
verify_jwt = false

[functions.woovi-webhook]
verify_jwt = false

[functions.admin-update-user-auth]
verify_jwt = false

[functions.admin-kid-actions]
verify_jwt = false

[functions.add-secondary-guardian]
verify_jwt = false

[functions.restore-admin-access]
verify_jwt = false

[functions.secondary-guardian-signup]
verify_jwt = false

[functions.restore-secondary-guardian-access]
verify_jwt = false
