project_id = "ylmrmidgxhcthwmoebzl"

[functions.asaas-pix]
verify_jwt = false

[functions.asaas-balance]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-pixout]
verify_jwt = false

[functions.asaas-approval-webhook]
verify_jwt = false

[functions.woovi-webhook]
verify_jwt = false
